"""Tool definitions for ClipCannon constellation/expression MCP tools."""

from __future__ import annotations

from mcp.types import Tool

CONSTELLATION_TOOL_DEFINITIONS: list[Tool] = [
    Tool(
        name="clipcannon_list_constellations",
        description=(
            "List all available behavioral constellations for a trained clone. "
            "Each constellation represents an emotional/behavioral state like "
            "'happy_storytelling' or 'emotional_recall' that groups multiple "
            "micro-expressions into a named, controllable behavior."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "person": {
                    "type": "string",
                    "default": "santa",
                    "description": "Clone identity name",
                },
            },
        },
    ),
    Tool(
        name="clipcannon_list_skills",
        description=(
            "List all available expression skills for a trained clone. "
            "Skills are named facial behaviors like 'genuine_laugh', "
            "'warm_smile', 'thoughtful_pause' extracted from training data."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "person": {
                    "type": "string",
                    "default": "santa",
                    "description": "Clone identity name",
                },
            },
        },
    ),
    Tool(
        name="clipcannon_clone_video",
        description=(
            "Generate a clone avatar video using EchoMimicV3 with LoRA identity lock "
            "and constellation-controlled expressions. This is DIFFERENT from "
            "clipcannon_generate_video (which uses LatentSync for lip-sync on existing video). "
            "This tool generates an ENTIRELY NEW video from scratch — the clone's face, body, "
            "expressions, and lip sync are all generated by the LoRA-trained model. "
            "The constellation controls emotional state and micro-expressions. "
            "Requires a trained LoRA for the specified person."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "person": {
                    "type": "string",
                    "default": "santa",
                    "description": "Clone identity name (must have trained LoRA)",
                },
                "audio_path": {
                    "type": "string",
                    "description": "Path to audio file (WAV, 16kHz). The clone will speak this audio.",
                },
                "constellation": {
                    "type": "string",
                    "default": "warm_conversational",
                    "description": (
                        "Behavioral constellation controlling expressions. Options: "
                        "warm_conversational, emotional_recall, happy_storytelling, "
                        "empathetic_concern, thoughtful_reflection, excited_sharing, "
                        "solemn_gravity, gentle_humor"
                    ),
                },
                "intensity": {
                    "type": "number",
                    "default": 0.8,
                    "description": "Expression intensity (0.0 = subtle, 1.0 = full)",
                },
                "duration_s": {
                    "type": "number",
                    "default": 0,
                    "description": "Video duration in seconds. 0 = match audio length.",
                },
                "output_path": {
                    "type": "string",
                    "default": "",
                    "description": "Output video path. Empty = auto-generate in project dir.",
                },
                "seed": {
                    "type": "integer",
                    "default": 42,
                    "description": "Random seed for reproducibility",
                },
            },
            "required": ["audio_path"],
        },
    ),
    Tool(
        name="clipcannon_expression_sequence",
        description=(
            "Generate a prompt sequence for a constellation over a duration. "
            "Returns per-frame expression prompts that can be used to control "
            "video generation. Useful for previewing what expressions will be "
            "generated before committing to full video generation."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "person": {
                    "type": "string",
                    "default": "santa",
                    "description": "Clone identity name",
                },
                "constellation": {
                    "type": "string",
                    "description": "Behavioral constellation name",
                },
                "duration_s": {
                    "type": "number",
                    "default": 5.0,
                    "description": "Sequence duration in seconds",
                },
                "intensity": {
                    "type": "number",
                    "default": 0.8,
                    "description": "Expression intensity",
                },
                "fps": {
                    "type": "integer",
                    "default": 25,
                    "description": "Frames per second",
                },
            },
            "required": ["constellation"],
        },
    ),
]
